druid:
  datasource:
    #打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 50
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
    filters: stat
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productmanage?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
     #初始化连接数量，最大最小连接数
    initial-size: 3
    min-idle: 3
#    max-active: 15
    max-wait: 60000 #获取连接等待超时的时间
    time-between-eviction-runs-millis: 600000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validation-query: SELECT 1 FROM DUAL #用来检测连接是否有效的sql，要求是一个查询语句
    test-while-idle: true #申请连接的时候检测
    test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    test-on-return: false #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能

mybatis:
  type-aliases-package: com.springboot.domain
